apiVersion: v1
kind: Pod
metadata:
  name: secrete-usage-via-env
spec:
  containers:
  - image: nginx
    name: ngnix-cotainer
    env: #static value env var
      - name: version #key 
        value: 1.0.0 #value 
      - name: environment
        value: DEV      
      - name: ENV_VAR_FROM_SECRET # the PORT from secret-from-env will be available as this name in env and this is env from secret
        valueFrom:
          secretKeyRef:
            name: secrete-from-env-file # secret name to pick a key 
            key: PORT # field you want to choose from the secret to make it available as  env var
