apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
spec:
  containers:
    - name: client
      image: busybox
      command:
        - sleep
        - "3600"

      volumeMounts:
        - name: shared-storage
          mountPath: /mnt/data

  volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: nfs-pvc